print("Primer fraccionario")
n1=int(input())
d1=int(input())
print("Segundo fraccionario")
n2=int(input())
d2=int(input())
print("El resultado de la suma de fracciones es: ", (n1*d2+n2*d1),"/",(d2*d1))
print("El resultado de la resta de fracciones es: ", (n1*d2-n2*d1),"/",(d2*d1))
print("El resultado de la multiplicacion es: ", (n1*n2),"/",(d1*d2))
print("El resultado de la division es: ", (n1*d2),"/",(n2*d1))